# Build and push the docker image

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  dockerId: ecsdigital
  imageName: selenium-jdk-gradle-dependencycheck

steps:
- task: Docker@2
  displayName: Build and Push
  inputs:
    command: buildAndPush
    containerRegistry: dockerRegistryServiceConnection1
    repository: $(dockerId)
    tags: |
      $(imageName):Build.BuildNumber
      $(imageName):latest