# Build and push the docker image

trigger:
- master

pr:
- master

schedules:
- cron: "0 12 * * 0"
  displayName: Weekly Sunday build
  branches:
    include:
    - master
  always: true

pool:
  vmImage: 'ubuntu-latest'

variables:
  dockerId: ecsdigital
  imageName: selenium-jdk-gradle-dependencycheck

steps:
- task: Docker@2
  displayName: Build and Push
  inputs:
    command: buildAndPush
    containerRegistry: dockerRegistryServiceConnection1
    repository: $(dockerId)/$(imageName)
    tags: |
      $(Build.BuildNumber)
      latest